name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*

env:
  #OPENTAP_COLOR: auto # github messes with the "auto" detection (i.e. it has no effect), and "always" breaks a lot of things
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_CONSOLE_ANSI_COLOR: true
  SMARTINSTALLER_IMAGE: ghcr.io/opentap/smartinstaller:2.2.0-beta.3

jobs:
  GetVersion:
    runs-on:
       group: OpenTAP-SpokeVPC
       labels:  [Linux, X64]
    container: ghcr.io/opentap/oci-images/build-dotnet:latest
    outputs:
      ShortVersion: ${{ steps.gitversion.outputs.ShortVersion }}
      LongVersion: ${{ steps.gitversion.outputs.LongVersion }}
      GitVersion: ${{ steps.gitversion.outputs.GitVersion }}
      SmartInstallerVersion: ${{ steps.smartInstallerVersion.outputs.ver }}
    steps:
      # The get-gitversion action installs OpenTAP and fetches with fetch-depth: 0
      - name: GitVersion
        id: gitversion
        uses: opentap/get-gitversion@bump-opentap
      - name: SmartInstallerVersion
        id: smartInstallerVersion
        run: echo "VER=$SMARTINSTALLER_IMAGE" >> $GITHUB_OUTPUT
