name: CI

on: [push]

jobs:
  GetVersion:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      AssemblyVersion: ${{ steps.asmVer.outputs.ver }}
      GitVersion: ${{ steps.gitVer.outputs.ver }}
    steps:
      - name: Install OpenTAP
        run: |
          wget -O opentap.tar https://www.opentap.io/docs/OpenTAP.9.16.2+f3c96b9f.tar
          tar -xf opentap.tar
          chmod u+x INSTALL.sh
          echo 'y' | ./INSTALL.sh
          ln -s -f "$HOME/.tap/tap" /usr/local/bin/tap
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: tap sdk gitversion --fields 3
        id: asmVer
        run: echo ::set-output name=ver::`tap sdk gitversion --fields 3`
      - name: tap sdk gitversion
        id: gitVer
        run: echo ::set-output name=ver::$(tap sdk gitversion)
      - run: $HOME/bin/tap sdk gitversion
      - run: echo $(tap sdk gitversion)
      - name: Print
        run: echo ${{ steps.gitVer.outputs.ver }}

  ##############
  ### BUILDS ###
  ##############
  Build-Linux:
    runs-on: ubuntu-latest
    container:
      #image: mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim
      image: mcr.microsoft.com/dotnet/sdk:6.0-focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Restore dependencies
      #   run: dotnet restore -c Release OpenTAP.sln
      # - name: Build
      #   run: dotnet build --no-restore -c Release OpenTAP.sln
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
      - name: Build
        run: dotnet publish -c Release OpenTAP.sln
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64-bin
          path: |
            bin/Release/publish/*

  Build-Win:
    runs-on: windows-2019
    strategy:
      matrix:
        Architecture: [x86, x64]
    needs: GetVersion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Stamp Version
        run: |
          $AssemblyVersion = "`"${{needs.GetVersion.outputs.AssemblyVersion}}.0`""
          $GitVersion = "`"${{needs.GetVersion.outputs.GitVersion}}`""
          Push-Location ./tap/Properties
          $AssemblyInfoFile = (Get-Content AssemblyInfo.cs.Template)
          $AssemblyInfoFile = ($AssemblyInfoFile) -replace '"AssemblyVersion"', $AssemblyVersion
          $AssemblyInfoFile = ($AssemblyInfoFile) -replace '"AssemblyFileVersion"', $AssemblyVersion
          $AssemblyInfoFile = ($AssemblyInfoFile) -replace '"AssemblyInformationalVersion"', $GitVersion
          $AssemblyInfoFile | Set-Content AssemblyInfo.cs
          cat AssemblyInfo.cs
          Pop-Location
      - name: Build
        run: |
          dotnet build -c Release /p:Platform=${{ matrix.Architecture }}
          dotnet build tap/tap.csproj -c Release /p:Platform=${{ matrix.Architecture }}
          get-content ./bin/Release/tap.runtimeconfig.json
          Remove-Item -recurse "bin\Release\Packages"
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: win-${{ matrix.Architecture }}-bin
          path: |
            bin/Release/*

  ##############
  ### TESTS ###
  ##############
  TestEngine:
    runs-on: windows-2022
    needs: Build-Win
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: win-x64-bin
          path: bin/
      - name: Test
        run: |
          $ErrorActionPreference = "Stop"
          dotnet vstest bin/OpenTap.UnitTests.dll --logger:"console;verbosity=detailed" -- RunConfiguration.TestSessionTimeout=1200000
      - uses: actions/upload-artifact@v2
        with:
          name: win-testresults
          path: |
            TestResult.xml

  TestPackage:
    runs-on: windows-2022
    needs: Build-Win
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: win-x64-bin
          path: bin/
      - name: Test
        run: |
          $ErrorActionPreference = "Stop"
          Copy-Item -r "Package.UnitTests/Packages" bin
          Copy-Item .\bin\runtimes\win-x64\native\git2-4aecb64.dll .\bin
          dotnet vstest bin/OpenTap.Package.UnitTests.dll --logger:"console;verbosity=detailed"
      - uses: actions/upload-artifact@v2
        with:
          name: win-testresults
          path: |
            TestResult.xml

  TestWindowsPlan:
    runs-on: windows-2022
    needs: Build-Win
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: win-x64-bin
          path: bin/
      - name: Test
        run: bin/tap.exe run tests/regression.TapPlan --verbose

  TestLinuxPlan:
    runs-on: ubuntu-20.04
    needs: Build-Win
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: linux-x64-bin
          path: bin/
      - name: Test
        run: bin/tap.exe run tests/regression.TapPlan --verbose
