name: Package Diff Commenter

on: [push]

# This grants access to the GITHUB_TOKEN so the action can make calls to GitHub's rest API
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  package-diff-comment:
    runs-on: ubuntu-latest
    name: package-diff-comment
    strategy:
      matrix:
        Package: [ win-x86, win-x64, linux-x64 ]
    needs:
      - Package-Win
      - Package-Linux
    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.Package }}-package
          path: .
      - name: Rename Package
        run: mv OpenTAP.*.TapPackage OpenTAP.TapPackage
      - name: Run comment action
        uses: alnlarsen/package-diff-comment@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: OpenTAP.TapPackage